version: "3"

services:
  web:
    build: .
    command: bash -c "python fintech_api/manage.py migrate && python fintech_api/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/code
    ports:
      - "8000:8000"
