# Generated by Django 3.1.5 on 2021-01-29 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.EmailField(max_length=30)),
                ('age', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('reference', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('account', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=30)),
                ('type', models.CharField(blank=True, choices=[('inflow', 'Inflow'), ('outflow', 'Outflow')], max_length=15)),
                ('category', models.CharField(max_length=15)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users_transactions.user')),
            ],
        ),
    ]
