# Generated by Django 3.1.5 on 2021-01-28 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_transactions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='reference',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
